import React from 'react';

const PrintTemplate = React.forwardRef(({ move, product, vendor, customer, warehouse }, ref) => {
  const formatDate = (dateString) => {
    if (!dateString) return '-';
    const date = new Date(dateString);
    return date.toLocaleDateString() + ' ' + date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  };

  const getMoveTypeLabel = (type) => {
    const labels = {
      'IN': 'RECEIPT',
      'OUT': 'DELIVERY ORDER',
      'INT': 'INTERNAL TRANSFER',
      'ADJ': 'STOCK ADJUSTMENT'
    };
    return labels[type] || type;
  };

  return (
    <div ref={ref} className="p-8 bg-white" style={{ fontFamily: 'Arial, sans-serif' }}>
      <div className="border-4 border-black p-6">
        {/* Header */}
        <div className="border-b-4 border-black pb-4 mb-4">
          <h1 className="text-4xl font-black uppercase mb-2">StockMaster IMS</h1>
          <h2 className="text-2xl font-bold uppercase">{getMoveTypeLabel(move.move_type)}</h2>
        </div>

        {/* Reference and Date */}
        <div className="grid grid-cols-2 gap-4 mb-4 border-b-2 border-black pb-4">
          <div>
            <p className="font-bold text-sm uppercase">Reference</p>
            <p className="text-xl font-black">{move.reference || `#${move.id}`}</p>
          </div>
          <div>
            <p className="font-bold text-sm uppercase">Date</p>
            <p className="text-lg">{formatDate(move.created_at)}</p>
          </div>
        </div>

        {/* Details */}
        <div className="mb-4 border-b-2 border-black pb-4">
          <div className="grid grid-cols-2 gap-4">
            <div>
              <p className="font-bold text-sm uppercase mb-1">Product</p>
              <p className="text-lg">{product?.name || `Product #${move.product_id}`}</p>
              <p className="text-sm text-gray-600">SKU: {product?.sku || 'N/A'}</p>
            </div>
            <div>
              <p className="font-bold text-sm uppercase mb-1">Quantity</p>
              <p className="text-2xl font-black">{move.quantity} {product?.uom || 'units'}</p>
            </div>
          </div>
        </div>

        {/* Source/Destination */}
        <div className="mb-4 border-b-2 border-black pb-4">
          {move.move_type === 'IN' && (
            <>
              <p className="font-bold text-sm uppercase mb-1">From (Vendor)</p>
              <p className="text-lg">{vendor?.name || move.source_location || 'N/A'}</p>
              {vendor && (
                <div className="text-sm text-gray-600 mt-1">
                  {vendor.email && <div>Email: {vendor.email}</div>}
                  {vendor.phone && <div>Phone: {vendor.phone}</div>}
                </div>
              )}
              <p className="font-bold text-sm uppercase mb-1 mt-4">To (Warehouse)</p>
              <p className="text-lg">{warehouse?.name || move.dest_location || 'N/A'}</p>
            </>
          )}
          {move.move_type === 'OUT' && (
            <>
              <p className="font-bold text-sm uppercase mb-1">From (Warehouse)</p>
              <p className="text-lg">{warehouse?.name || move.source_location || 'N/A'}</p>
              <p className="font-bold text-sm uppercase mb-1 mt-4">To (Customer)</p>
              <p className="text-lg">{customer?.name || move.dest_location || 'N/A'}</p>
              {customer && (
                <div className="text-sm text-gray-600 mt-1">
                  {customer.email && <div>Email: {customer.email}</div>}
                  {customer.phone && <div>Phone: {customer.phone}</div>}
                  {customer.address && <div>Address: {customer.address}</div>}
                </div>
              )}
            </>
          )}
          {move.move_type === 'INT' && (
            <>
              <p className="font-bold text-sm uppercase mb-1">From Warehouse</p>
              <p className="text-lg">{move.source_location || 'N/A'}</p>
              <p className="font-bold text-sm uppercase mb-1 mt-4">To Warehouse</p>
              <p className="text-lg">{move.dest_location || 'N/A'}</p>
            </>
          )}
        </div>

        {/* Status */}
        <div className="mb-4">
          <p className="font-bold text-sm uppercase mb-1">Status</p>
          <p className="text-lg font-black uppercase">{move.status}</p>
        </div>

        {/* Footer */}
        <div className="border-t-4 border-black pt-4 mt-4 text-center text-sm">
          <p className="font-bold">Generated by StockMaster Inventory Management System</p>
          <p className="text-gray-600">Print Date: {new Date().toLocaleString()}</p>
        </div>
      </div>
    </div>
  );
});

PrintTemplate.displayName = 'PrintTemplate';

export default PrintTemplate;

